compile:
	java -cp antlr-3.5.2-complete.jar org.antlr.Tool hw2.g
	javac -cp antlr-3.5.2-complete.jar:. testhw2.java
test1:
	java -cp antlr-3.5.2-complete.jar:. testhw2 test1.c
test2:
	java -cp antlr-3.5.2-complete.jar:. testhw2 test2.c
test3:
	java -cp antlr-3.5.2-complete.jar:. testhw2 test3.c
